import { Hero, InfoGrid, ProductGrid, Header, Footer, ProductDetail, TextContent, VideoGrid, ImageBox, Newsletter, CustomerProfile, Testimonials, FAQ, Banner, LogoCloud, Countdown, Features, UniversalGrid, PricingTable, StatsSection, CallToAction, Divider, Spacer, Gallery, Accordion, Tabs, Timeline, TeamGrid, ContactForm, ComparisonTable } from "@repo/ui-bricks";

export const RENDER_MAP: Record<string, any> = {
    Header,
    Footer,
    Hero,
    BenefitsGrid: InfoGrid,
    InfoGrid,
    ProductGrid,
    ProductDetail,
    TextContent,
    VideoGrid,
    ImageBox,
    Newsletter,
    CustomerProfile,
    Testimonials,
    FAQ,
    Banner,
    LogoCloud,
    Countdown,
    Features,
    UniversalGrid,
    PricingTable,
    StatsSection,
    CallToAction,
    Divider,
    Spacer,
    Gallery,
    Accordion,
    Tabs,
    Timeline,
    TeamGrid,
    ContactForm,
    ComparisonTable
};
